/* This file was generated by the Hex-Rays decompiler version 9.2.0.250908.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall sub_1C7330(); // weak
unsigned __int64 __fastcall sub_1D3169();
void sub_1D3188();
void nullsub_3();
char sub_1D3681();


//----- (00000000001C7330) ----------------------------------------------------
__int64 __fastcall sub_1C7330()
{
  unsigned int v0; // ebx

  return v0;
}
// 1C7330: variable 'v0' is possibly undefined
// 1C7330: using guessed type __int64 __fastcall sub_1C7330();

//----- (00000000001D3169) ----------------------------------------------------
unsigned __int64 __fastcall sub_1D3169()
{
  unsigned __int64 result; // rax

  __asm { syscall; LINUX - }
  if ( result >= 0xFFFFFFFFFFFFF000LL )
    __halt();
  return result;
}
// 1D3173: variable 'result' is possibly undefined

//----- (00000000001D3188) ----------------------------------------------------
void sub_1D3188()
{
  ;
}

//----- (00000000001D3681) ----------------------------------------------------
char sub_1D3681()
{
  return MEMORY[0xC6587FB5F6290169];
}

// nfuncs=13 queued=4 decompiled=4 lumina nreq=0 worse=0 better=0
// ALL OK, 4 function(s) have been successfully decompiled
